mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
spring:
  application:
    name: ShardingJDBC
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.50.41:3306/test
#    username: root
#    password: test1
#    type: com.alibaba.druid.pool.DruidDataSource

  #  主库数据源
  shardingsphere:
    props:
      sql:
        # 日志打印SQL语句
        show: true
    # 读写分离配置
    masterslave:
      # dataSource 随意给masterslave 设置一个名字
      name: dataSource
      # 负载均衡算法 round_robin随机（内置算法）
      load-balance-algorithm-type: round_robin
      # 主库
      master-data-source-name: ds0
      # 从库
      slave-data-source-names: ds1,ds2
    datasource:
      # 数据源名称定义
      names: ds0,ds1,ds2
      # 主数据源
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.50.41:3306/test
        username: root
        password: test1
      # 从数据源
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.50.42:3306/test
        username: root
        password: test1
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.50.43:3306/test
        username: root
        password: test1
## 接口文档配置
#knife4j:
#  # 开启登录访问
#  basic:
#    enable: true
#    username: root
#    password: 123456
#  enable: true
#  setting:
#    language: zh_cn
